### PR TITLE
Levi/racecondition

### PR DESCRIPTION
**Pull request by levigroker**
This fixes a witnessed race condition with filesystem access when running optimized code on macOS which prevented the `createFile` function from being successful. This also addresses other similar potential issues by removing unnecessary calls to file system functions in the `init` method.

### CODE REVIEW

**Comment by levigroker** [comment]
Seems to be a configuration issue... ?

```
2019-05-21T22:02:35.4953901Z [command]/bin/bash --noprofile --norc /__w/_temp/6763c081-68bf-460a-820c-3380ba38ce89.sh
2019-05-21T22:02:36.4074829Z warning: you may be able to install zlib using your system-packager:
2019-05-21T22:02:36.4075604Z      apt-get install zlib
2019-05-21T22:02:36.4075903Z 
2019-05-21T22:02:36.4719049Z [1/4] Compiling Swift Module 'ZIPFoundation' (7 sources)
2019-05-21T22:02:37.8868394Z <module-includes>:1:10: note: in file included from <module-includes>:1:
2019-05-21T22:02:37.8868982Z #include "shim.h"
2019-05-21T22:02:37.8869186Z          ^
2019-05-21T22:02:37.8869629Z /__w/1/s/Sources/CZLib/shim.h:15:9: error: 'zlib.h' file not found
2019-05-21T22:02:37.8869755Z #import <zlib.h>
2019-05-21T22:02:37.8869894Z         ^
2019-05-21T22:02:37.8870238Z /__w/1/s/Sources/ZIPFoundation/Data+Compression.swift:208:8: error: could not build C module 'CZlib'
2019-05-21T22:02:37.8870434Z import CZlib
2019-05-21T22:02:37.8870537Z        ^
2019-05-21T22:02:37.9821225Z ##[error]Bash exited with code '1'.
2019-05-21T22:02:38.0212087Z ##[section]Finishing: Linux Swift 5.0
```

**Comment by weichsel** [comment]
> Seems to be a configuration issue... ?
I just updated the CI configuration. 
Looks like the official Swift 5 Docker image no longer has zlib pre-installed. I switched to a user provided image that includes zlib. Please pull in from `development`.

**Comment by levigroker** [comment]
Updated.

**Comment by levigroker** [comment]
You're welcome! Sorry I didn't have time to provide a test case which exhibited the race condition... as you might expect, that'd be a bit challenging.

**Pull request merged**
