### PR TITLE
Fixes so repo builds with Xcode 15

### PR DESCRIPTION
**Pull request by JagCesar**
This PR Adds the os(xrOS) conditional check, without it the build fails as it falls into the #else block.

This is required to build with Xcode 15 beta 6

### CODE REVIEW

**Comment by osy** [comment]
FYI os(xrOS) does not work since beta 4. It should be os(visionOS). See https://github.com/weichsel/ZIPFoundation/compare/development...osy:ZIPFoundation:development

**Comment by JagCesar** [comment]
> FYI os(xrOS) does not work since beta 4. It should be os(visionOS). See [development...osy:ZIPFoundation:development](https://github.com/weichsel/ZIPFoundation/compare/development...osy:ZIPFoundation:development)

I don't think that's correct, I'm building one of our products using my fork and it builds, archives and uploads to App Store Connect without issues. Building on Xcode Cloud using Xcode beta 6. 🤷‍♂️

**Comment by osy** [comment]
I’m on beta 5 so maybe it’s a recent change? Regardless Apple is sticking to visionOS as marketing and changed all their API headers to refer to visionOS. I don’t think people should refer to xrOS.

**Comment by weichsel** [comment]
@JagCesar Thanks for the PR! 
I think @osy is right - Apple switched to `visionOS` for conditional compilation. Will merge and then change that on `development`.

**Pull request merged**
